service: nodeless

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  optimize:
    handler: optimize.handler
    environment:
      bucket: serverlessNodeless
    events:
      - s3:
          bucket: serverlessNodeless
          event: s3:ObjectCreated:*
          rules:
            - prefix: upload/
            - suffix: .jpg
      - s3:
          bucket: serverlessNodeless
          event: s3:ObjectCreated:*
          rules:
            - prefix: upload/
            - suffix: .png